############################################################
#							   #
# file: Makefile					   #
#							   #
# csd5178 ASPRIDIS NIKOLAOS				   #
#							   #
# 06/11/24						   #
#							   #
# HY_345 assignment_2					   #
#							   #
############################################################

all : assign2

assign2 : main.c
	gcc -Wall -ansi -pedantic main.c -pthread -o assign2




clean :
	rm -f assign2
