###################################################
#
# file: Makefile
#
# Aspridis Nikolaos
# csd5178
# 
#
##################################################


all : prompt

prompt : main.c
	gcc -Wall -ansi -pedantic main.c -o prompt



clean :
	rm -f prompt
