#################################
# 				#
# ASPRIDIS NIKOLAOS csd5178 	#
#  				#
# hy-345 2024			#
#				#
#################################

all : test

test : test.c
	gcc -Wall -pedantic test.c -o test



clean :
	rm -f test
